#!/usr/bin/env dotnet
#:property Authors=Richard Lander
#:property Description=A simple .NET tool that prints dotnetbot
#:property PackageId=dotnetsay
#:property PackageLicenseExpression=MIT
#:property PackageReadmeFile=README.md
#:property PackAsTool=true
#:property PublishRepositoryUrl=true
#:property RollForward=LatestMajor
#:property TargetFramework=net8.0
#:property ToolCommandName=dotnetsay
#:property VersionPrefix=3.0.2

string message = "Welcome to dotnetsay, a basic .NET tool!";

if (Console.IsInputRedirected)
{
    message = Console.In.ReadToEnd();
}
else if (args.Length > 0)
{
    message = string.Join(" ", args);
}

Console.WriteLine(GetBot(message));

static string GetBot(string message)
{
    return @$"
    {message}
    __________________
                      \
                       \
                          ....
                          ....'
                           ....
                        ..........
                    .............'..'..
                 ................'..'.....
               .......'..........'..'..'....
              ........'..........'..'..'.....
             .'....'..'..........'..'.......'.
             .'..................'...   ......
             .  ......'.........         .....
             .                           ......
            ..    .            ..        ......
           ....       .                 .......
           ......  .......          ............
            ................  ......................
            ........................'................
           ......................'..'......    .......
        .........................'..'.....       .......
     ........    ..'.............'..'....      ..........
   ..'..'...      ...............'.......      ..........
  ...'......     ...... ..........  ......         .......
 ...........   .......              ........        ......
.......        '...'.'.              '.'.'.'         ....
.......       .....'..               ..'.....
   ..       ..........               ..'........
          ............               ..............
         .............               '..............
        ...........'..              .'.'............
       ...............              .'.'.............
      .............'..               ..'..'...........
      ...............                 .'..............
       .........                        ..............
        .....
";
}
